### ISSUE TITLE
"undefined method `within_frame' " using SitePrism >= 2.12 and capybara >= 2.12 version (fixed dependency in siteprism)

### ISSUE THREAD

**Issue by lexxborn** [natritmeyer/site_prism#274]
## Environment
- Operating System: Mac, Windows 10 / 8 / 7
- What Gems / Versions: SitePrism 2.12 with Capybara 2.12 up to 2.18
- RSpec tests
- Chrome latest version and selenium-webdriver-3.12.0 

## Expected Behavior
Tests should run without errors (as before)

## Actual Behavior
If we run the tests with this combination (siteprism 2.12 & capybara 2.12-2.18) we get many errors in the logs: 

"undefined method `within_frame' for Obsolete #<Capybara::Node::Element>:Capybara::Node::Element"

With the SitePrism **2.11** version and any version of capybara all works fine again. Because the 2.12 version of siteprism has a fixed dependency to capybara (from 2.12 version) we have to downgrade siteprism to get working tests again.

Exception:
./gems/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
./gems/gems/site_prism-2.13/lib/site_prism/element_container.rb:57:in `block in iframe'
...........
./gems/gems/site_prism-2.13/lib/site_prism/element_container.rb:58:in `block (2 levels) in iframe'
./gems/gems/capybara-2.18.0/lib/capybara/session.rb:426:in `within_frame'
./gems/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
./gems/gems/site_prism-2.13/lib/site_prism/element_container.rb:57:in `block in iframe'
...........
./gems/gems/rspec-example_steps-3.0.2/lib/rspec/example_steps/reporter.rb:9:in `process_example_step'
./gems/gems/rspec-example_steps-3.0.2/lib/rspec/example_steps/example_group.rb:16

...........
./gems/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
./gems/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
./gems/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
./gems/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
./gems/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'    

We discover some changes that could be related to that issue: 
https://github.com/natritmeyer/site_prism/commit/296c932409fb51484d2897a0283dfaf6baa0645b#diff-0142fe7beaa583d4ce8030ab2a152817L58

## Steps to reproduce
RSpec tests using described versions of siteprism and capybara. The tests should test iFrames.

**Comment by luke-hill** [comment]
Can you provide a sample page / code to run against?
Unsure how you are obtaining a dual element? `Obsolete #Capybara::Node::Element:Capybara::Node::Element` - that doesn't really make sense.

**Comment by kassi** [comment]
That's a formatting issue. I'll paste the correct output.
```
undefined method `within_frame' for Obsolete #<Capybara::Node::Element>:Capybara::Node::Element
Did you mean?  with_warnings (NoMethodError)
NoMethodError:
undefined method `within_frame' for Obsolete #<Capybara::Node::Element>:Capybara::Node::Element
Did you mean?  with_warnings
./gems/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
./gems/gems/site_prism-2.13/lib/site_prism/element_container.rb:57:in `block in iframe'
./spec/acceptance_tests/sections/client_paydata_section.rb:138:in `update_to_credit_card'
```

I can paste the code snippet that leads to this failure, but since it's part of a bigger test suite you can't simply run it. Maybe we can extract it somehow.

**Comment by kassi** [comment]
@luke-hill please have a look at the gist: https://gist.github.com/kassi/a6dbe86d085e9eed73c2eec7bb00c8a4

I extracted the parts I think are relevant for the workflow and marked where it fails.

Additionally I checked again: It's working with capybara 2.18.0 and site_prism 2.11 and fails with site_prism 2.12 and any (2.12..2..18) capybara version.

**Comment by luke-hill** [comment]
Have you a url I can run this against? I can't test this code without a physical page to hit.

**Comment by kassi** [comment]
@luke-hill for the outside world this is actually only available on production and inside the member area. You would have to register first. The test environment is not reachable.
Maybe it's better if I get a demo app running, but this may take some time since I need to find out what I need to include.

**Comment by luke-hill** [comment]
Does this line work? - https://gist.github.com/kassi/a6dbe86d085e9eed73c2eec7bb00c8a4#file-client_paydata_section-rb-L27

Can you alter Line28-30 to instead do the following
set your `cc_iframe` as an `element` and write the following

```
within_iframe cc_iframe do
  update_to_credit_card(number)
end
```

Let me know if the above works - If it does, then you have a brief work-around for now.

Also let men know if the sample page we have in our test_site directory helps at all (There are a couple of Iframe integration tests we have)

Code: https://github.com/natritmeyer/site_prism/tree/master/test_site/html
Integration Tests: https://github.com/natritmeyer/site_prism/blob/master/features/iframes.feature

**Comment by kassi** [comment]
Thanks for patch. Unfortunately I'm getting the same error. Interestingly it says:
```
Failure/Error:
  within_iframe cc_iframe do
    update_to_credit_card(credit_card)
  end

NoMethodError:
  undefined method 'within_frame' for Obsolete #<Capybara::Node::Element>:Capybara::Node::Element
  Did you mean?  with_warnings
```
i.e. it's telling me it doesn't find `within_frame` - not `within_iframe`.

**Comment by luke-hill** [comment]
Right. If that is failing then it's something with your setup. Unfortunately I can't triage it until I can get a fully reproducible sample. Did you change `cc_iframe` to a SitePrism::Element ?

Ideally I would need a github repo I can clone and just type `rspec` in. So I can see the failing tests. We don't have a huge amount of unit / feature tests for iFrames, but we do have a few that check locators can be found.

I'll give you a short while to see if you can reproduce a sample case for me, but failing that, there is nothing I can act on here. I'm reasonably confident that this is an issue with the way you have setup your suite.

**Comment by kassi** [comment]
@luke-hill I managed to create a new rails app and boiling it down to the bare minimum which lets the test fail: https://github.com/kassi/site_prism_iframe_demo
I tried to keep our Page and Section structure because this might be part of the problem.
Thanks for waiting

**Comment by roryp2** [comment]
Seeing the exact same issue as well when I upgrade to a version above 2.12

**Comment by luke-hill** [comment]
Yep. I know that we have enough info to triage. However Pull Requests are welcome.

At the moment, the priority is getting 2.15 cut. Which will feature experimental Capybara 3 support and a fix for implicit waiting on all DSL method signatures. Only after that will there be any availability to look into this.

If you try pull down the repo that @kassi added then maybe you can look into this as well?

**Comment by ineverov** [comment]
@luke-hill please close this issue

**Comment by luke-hill** [comment]
Fixed and released in v2.15.1
